### ISSUE TITLE
Add Style Guide for Docs

### ISSUE THREAD

**Issue by joaedwar** [Lookyloo/docs#11]
## What is changing? 
*(Please include as many details as possible)*
Add style guide for documentation changes

## How will this impact users?
Make writing docs for the site consistent and should be added to contrib guide. 

## To which release does this apply?

- [x] Current release
- [ ] Future release 

## Context
Link to associated PRs or issues from other repos here.

**Comment by Rafiot** [comment]
See: https://www.lookyloo.eu/docs/main/contributor-guide-docs.html
