### ISSUE TITLE
Link to unavailable website

### ISSUE THREAD

**Issue by wagner-certat** [Lookyloo/docs#24]
https://www.lookyloo.eu/docs/main/lookyloo-integration.html links to https://phishing-initiative.lu/ but that page is unavailable. Not sure if there's new URL or if the paragraph is obsolete.

**Comment by Rafiot** [comment]
True, phishing initiative doesn't exists anymore, it is .fr now. I'll fix that, thank you for the notification.

**Comment by Rafiot** [comment]
Fixed -> https://github.com/Lookyloo/docs/commit/256664d3dc3efae7cf151ac02a51eb7ecaedbe60
