### ISSUE TITLE
Rename main branch from master to main

### ISSUE THREAD

**Issue by Rafiot** [Lookyloo/docs#3]
## What is changing? 

Every repository in the Lookyloo org is using `main` as the main branch, in order to be consistent, we should move the docs to use the same scheme.

## How will this impact users?

They will need to rename their branch locally, as described here: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

## To which release does this apply?

- [x] Current release

## Additional information

We need to update the configuration of the repository on github too, and remove the existing `master` branch to avoid confusion.

**Comment by joaedwar** [comment]
This has been resolved
